server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://mysql6.sqlpub.com:3311/madgod?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: madgod
    password: JAl5GKI9UnkPBYJk
    driver-class-name: com.mysql.cj.jdbc.Driver